# Generated by Django 2.2.28 on 2024-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('energy', models.IntegerField(default=100)),
                ('happiness', models.IntegerField(default=100)),
                ('hunger', models.IntegerField(default=0)),
            ],
        ),
    ]
