# Generated by Django 2.2.28 on 2024-11-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='espece',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='species',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='happiness',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='hunger',
        ),
        migrations.AddField(
            model_name='animal',
            name='etat',
            field=models.CharField(choices=[('affamé', 'Affamé'), ('repus', 'Repus'), ('fatigué', 'Fatigué'), ('endormi', 'Endormi')], default='endormi', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animalerie.Equipement'),
        ),
    ]
