# Generated by Django 2.2.28 on 2024-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0002_auto_20241117_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='type',
            field=models.CharField(choices=[('mangeoire', 'Mangeoire'), ('nid', 'Nid'), ('roue', 'Roue'), ('litière', 'Litière')], default='litière', max_length=50),
            preserve_default=False,
        ),
    ]
